### ISSUE TITLE
Error: Script error for: newOrderNotification

### ISSUE THREAD

**Issue by refueledinc** [jahvi/new-order-notification#1]
Magento 2.2.3, developer mode

On checkout we are seeing errors with this module enabled which is preventing the checkout from fully loading and allowing people to checkout.

```
Loading failed for the <script> with source “/static/frontend/Magento/luma/en_US/newOrderNotification.js”.
Error: Script error for: newOrderNotification
http://requirejs.org/docs/errors.html#scripterror
```

**Comment by jahvi** [comment]
Thanks for reporting this I'll see if I can replicate

**Comment by refueledinc** [comment]
It is also throwing JS errors on the category and product pages:

```
static/frontend/Magento/luma/en_US/Jahvi_NewOrderNotification/js/modernizr.custom/modernizr.js
Error: Script error for: modernizr/modernizr
http://requirejs.org/docs/errors.html#scripterror
```

**Comment by jahvi** [comment]
I haven't managed to replicate the issue, can you confirm the files exist in the `pub` folder?

**Comment by refueledinc** [comment]
I do not see the `Jahvi_NewOrderNotification` folder in `pub`, but I do see other vendors in that folder.

**Comment by jahvi** [comment]
I see, have you set up the Pusher credentials in the backend? If so have you tried running `setup:static-content:deploy`? If it's in developer mode you shouldn't have to but it's worth trying

**Comment by refueledinc** [comment]
Yes, we have Pusher setup. I tried to force static deploy in development mode but it did not help fix the error.

**Comment by 29sunil** [comment]
We get this error
Fatal error: Uncaught Error: Class 'Pusher\Pusher' not found in /var/www/html/newaugm3/app/code/Jahvi/NewOrderNotification/Observer/DisplayNotification.php:76 Stack trace: #0 /var/www/html/newaugm3/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Jahvi\NewOrderNotification\Observer\DisplayNotification->execute(Object(Magento\Framework\Event\Observer)) #1 /var/www/html/newaugm3/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Jahvi\NewOrderNotification\Observer\DisplayNotification), Object(Magento\Framework\Event\Observer)) #2 /var/www/html/newaugm3/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /var/www/html/newaugm3/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('checkout_onepag...', Array) #4 /var/www/html/newaugm3/vendor/magento/module-checkout/Controlle in /var/www/html/newaugm3/app/code/Jahvi/NewOrderNotification/Observer/DisplayNotification.php on line 76

**Comment by jahvi** [comment]
Refer to #2
