### ISSUE TITLE
Class 'Pusher\Pusher' not found

### ISSUE THREAD

**Issue by milanwebcreta** [jahvi/new-order-notification#2]
Uncaught Error: Class 'Pusher\Pusher' not found in /home/294362.cloudwaysapps.com/ubxgngjzre/public_html/app/code/Jahvi/NewOrderNotification/Observer/DisplayNotification.php:76

**Comment by jahvi** [comment]
You need to install this with composer as per the [Installation Instructions](https://github.com/jahvi/magento2-new-order-notification#installation-instructions) so you get all the dependencies, don't use it directly in the `app/code` folder.
